apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: weatherapp-service
spec:
  selector:
    app: weatherapp
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5000
  type: LoadBalancer  
