apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  namespace: myapp
spec:
  selector:
    app: weatherapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
